import { Component, type ErrorInfo, type ReactNode, useEffect, useMemo, useRef, useState } from 'react'
import { BookOpen, BriefcaseBusiness, Building2, Check, ChevronRight, ClipboardCheck, Download, Factory, Gauge, Headphones, LayoutDashboard, Menu, RotateCcw, Save, Settings2, Table2, Upload, UserRound, Wrench, X } from 'lucide-react'
import { askQuestions, companyCards, dfmaTopics, questions, responsibilities, stories } from './data/content'
import { defaultState, emptyQuestion, loadState, parseImport, saveState } from './lib/storage'
import { scoreAnswer } from './lib/scoring'
import type { AppState, QuestionState, Section } from './types'

const nav: {id:Section;label:string;icon:typeof LayoutDashboard}[] = [
  {id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'company',label:'Company',icon:Building2},{id:'role',label:'Role',icon:BriefcaseBusiness},
  {id:'background',label:'My Background',icon:UserRound},{id:'matrix',label:'Experience Matrix',icon:Table2},{id:'questions',label:'Question Bank',icon:BookOpen},
  {id:'mock',label:'Mock Interview',icon:Headphones},{id:'dfma',label:'DFMA Fundamentals',icon:Settings2},{id:'ask',label:'Questions for Reframe',icon:Wrench},{id:'final',label:'Final Review',icon:ClipboardCheck}
]
const title:Record<Section,string> = {dashboard:'Interview readiness',company:'Know the system',role:'Understand the bridge',background:'Position your experience',matrix:'Connect evidence to need',questions:'Practice the point, not a script',mock:'Run the conversation',dfma:'DFMA fundamentals',ask:'Ask like an owner',final:'Final interview sheet'}
const logistics = ['Confirm interviewer name and position','Review job posting','Charge phone','Test reception','Find quiet room','Keep résumé available','Keep job description available','Have water','Keep notebook and pen','Silence notifications','Join or answer five minutes early','Send a follow-up email after the interview']

class ErrorBoundary extends Component<{children:ReactNode},{error:boolean}> {
  state={error:false}
  static getDerivedStateFromError(){return {error:true}}
  componentDidCatch(error:Error, info:ErrorInfo){console.error(error,info)}
  render(){return this.state.error?<main className="fatal"><Factory/><h1>The guide hit a snag.</h1><p>Your saved study data is still local. Reload the page to continue.</p><button onClick={()=>location.reload()}>Reload guide</button></main>:this.props.children}
}

function App(){
  const [section,setSection]=useState<Section>('dashboard')
  const [state,setState]=useState<AppState>(()=>loadState())
  const [menu,setMenu]=useState(false)
  const [saved,setSaved]=useState(true)
  const importRef=useRef<HTMLInputElement>(null)
  useEffect(()=>{setSaved(false);const id=setTimeout(()=>{saveState(state);setSaved(true)},250);return()=>clearTimeout(id)},[state])
  const update=(patch:Partial<AppState>)=>setState(s=>({...s,...patch}))
  const practiced=Object.values(state.questions).filter(q=>q.practiced).length
  const confident=Object.values(state.questions).filter(q=>q.confidence>=4).length
  const score=Math.round((state.reviewedCompany.length/companyCards.length*25)+(practiced/questions.length*35)+(confident/questions.length*25)+(state.selectedAsk.length/3*15))
  const navigate=(id:Section)=>{setSection(id);setMenu(false);window.scrollTo(0,0)}
  const exportData=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='reframe-field-guide.json';a.click();URL.revokeObjectURL(a.href)}
  const onImport=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{setState(parseImport(await file.text()))}catch(err){alert(err instanceof Error?err.message:'Import failed')}e.target.value=''}
  const reset=()=>{if(confirm('Reset all local progress and notes? This cannot be undone unless you exported a backup.'))setState(defaultState())}
  let body:ReactNode
  switch(section){
    case 'dashboard':body=<Dashboard score={Math.min(score,100)} practiced={practiced} confident={confident} reviewed={state.reviewedCompany.length} navigate={navigate}/>;break
    case 'company':body=<Company state={state} update={update}/>;break
    case 'role':body=<Role state={state} update={update}/>;break
    case 'background':body=<Background state={state} update={update}/>;break
    case 'matrix':body=<Matrix state={state} update={update}/>;break
    case 'questions':body=<QuestionBank state={state} setState={setState}/>;break
    case 'mock':body=<Mock state={state} setState={setState}/>;break
    case 'dfma':body=<Dfma/>;break
    case 'ask':body=<Ask state={state} update={update}/>;break
    case 'final':body=<Final state={state} update={update}/>;break
  }
  return <ErrorBoundary><div className="app">
    <aside className={menu?'rail open':'rail'} aria-label="Main navigation">
      <div className="brand"><span className="brand-mark"><Factory/></span><div><strong>REFRAME /<br/>FIELD GUIDE</strong><small>DFMA ENGINEER INTERVIEW PREP</small></div><button className="close-menu" onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button></div>
      <nav>{nav.map(item=><button key={item.id} className={section===item.id?'active':''} onClick={()=>navigate(item.id)}><item.icon/><span>{item.label}</span></button>)}</nav>
      <button className="reset-link" onClick={reset}><RotateCcw/>Reset study data</button>
    </aside>
    {menu?<button className="scrim" onClick={()=>setMenu(false)} aria-label="Close navigation"/>:null}
    <div className="workspace">
      <header className="utility"><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><span className="save-state"><Save/>{saved?'LOCAL SAVE · UP TO DATE':'SAVING…'}</span><button onClick={exportData}><Download/>Export</button><button onClick={()=>importRef.current?.click()}><Upload/>Import</button><input ref={importRef} type="file" accept="application/json" hidden onChange={onImport}/></header>
      <main><div className="page-head"><h1>{title[section]}</h1><span>{nav.find(n=>n.id===section)?.label}</span></div>{body}</main>
    </div>
  </div></ErrorBoundary>
}

function Dashboard({score,practiced,confident,reviewed,navigate}:{score:number;practiced:number;confident:number;reviewed:number;navigate:(s:Section)=>void}){
  const days=Math.max(0,Math.ceil((new Date('2026-07-30T09:00:00-04:00').getTime()-Date.now())/86400000))
  const sequence:[string,string,Section][]=[['Review company and role','Understand Reframe’s system and the DFMA bridge.','company'],['Refine personal introduction','Keep the point, proof, and role connection clear.','background'],['Build five core project stories','Anchor each story in observable evidence.','matrix'],['Practice phone-screen questions','Speak concisely without memorizing scripts.','questions'],['Review DFMA terminology','Translate principles into modular-housing examples.','dfma'],['Select interviewer questions','Choose three primary questions and two backups.','ask'],['Complete a final mock interview','Find weak answers before Thursday.','mock']]
  return <><section className="date-band"><div><small>INTERVIEW DATE</small><strong>Thursday, July 30</strong></div><div><small>DAYS REMAINING</small><strong className="orange">{days} days</strong></div></section>
  <section className="readiness"><div><small>OVERALL PREPARATION SCORE</small><strong>{score}%</strong></div><div className="meter"><i style={{width:`${score}%`}}/><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div></section>
  <section className="metrics"><Metric icon={BookOpen} label="Questions practiced" value={practiced} total={questions.length}/><Metric icon={Check} label="Confident" value={confident}/><Metric icon={Wrench} label="Needs work" value={Math.max(practiced-confident,0)} orange/><Metric icon={Factory} label="Company topics reviewed" value={reviewed} total={companyCards.length}/></section>
  <section className="dashboard-grid"><div className="sequence"><h2>Recommended study sequence</h2>{sequence.map((s,i)=><button onClick={()=>navigate(s[2])} key={s[0]}><b>{i+1}</b><span><strong>{s[0]}</strong><small>{s[1]}</small></span><ChevronRight/></button>)}<button className="primary" onClick={()=>navigate('company')}>Continue studying <ChevronRight/></button></div>
  <div className="side-list"><h2>Strongest stories</h2>{stories.slice(0,3).map((s,i)=><div key={s.id}><b>0{i+1}</b><span>{s.title}<small>{s.relevance}</small></span></div>)}</div>
  <div className="side-list weak"><h2>Current weak areas</h2>{['Structural drawing fluency','Revit / BIM workflow','Modular code & release process'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}<small>Prepare an honest bridge, not a defensive answer.</small></span></div>)}</div></section></>
}
function Metric({icon:Icon,label,value,total,orange}:{icon:typeof BookOpen;label:string;value:number;total?:number;orange?:boolean}){return <div className={orange?'metric orange':'metric'}><Icon/><span><small>{label}</small><strong>{value}{total?<em> / {total}</em>:null}</strong></span></div>}
function Company({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){return <div className="study-list">{companyCards.map((c,i)=>{const checked=state.reviewedCompany.includes(c.id);return <article key={c.id} className="study-card"><div className="card-no">0{i+1}</div><div><h2>{c.title}</h2><p className="lead">{c.summary}</p><dl><div><dt>Why it matters</dt><dd>{c.matters}</dd></div><div><dt>DFMA connection</dt><dd>{c.role}</dd></div><div><dt>Talking point</dt><dd>“{c.talking}”</dd></div></dl></div><label className="review-check"><input type="checkbox" checked={checked} onChange={()=>update({reviewedCompany:checked?state.reviewedCompany.filter(x=>x!==c.id):[...state.reviewedCompany,c.id]})}/><span><Check/>Reviewed</span></label></article>})}</div>}
function Role({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){return <><p className="intro-copy">Part builder, part engineer, part translator. The DFMA Engineer makes sure what is designed can be built in the factory and installed in the field.</p><div className="responsibilities">{responsibilities.map(([stage,item])=><div key={item}><span className="stage">{stage}</span><strong>{item}</strong><fieldset aria-label={`Self assessment for ${item}`}><legend>Self assessment</legend>{[1,2,3,4,5].map(n=><button key={n} className={(state.responsibilityRatings[item]??0)>=n?'selected':''} onClick={()=>update({responsibilityRatings:{...state.responsibilityRatings,[item]:n}})} aria-label={`${n} of 5`}>{n}</button>)}</fieldset></div>)}</div><section className="traits"><h2>Candidate characteristics</h2><p>Hands-on building knowledge · drawing literacy · early buildability judgment · CAD/BIM comfort · factory experience · cross-functional communication · strong documentation · follow-through · desk-and-floor range</p></section></>}
function Background({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){const keywords=['Production systems','CAD & parametric modeling','Rapid prototyping','Automation support','Design-to-build translation'];return <div className="editor-layout"><section><h2>Professional positioning</h2><p className="lead">A hands-on systems optimization and mechanical design professional working at the intersection of digital modeling, rapid prototyping, automation, and production operations.</p><h2>60–90 second introduction</h2><textarea value={state.intro} onChange={e=>update({intro:e.target.value})} rows={14}/><MemoryMap text={state.intro} keywords={keywords}/></section><aside><h2>Education: direct, not defensive</h2><blockquote>My education in architectural studies gave me a strong foundation in drafting, three-dimensional modeling, design thinking, and the relationship between design intent and physical construction. I ultimately took a more applied path into manufacturing and automation, where I have continued developing those skills through hands-on projects, independent study, and progressively greater responsibility.</blockquote><h2>Technical tools</h2><p className="tool-list">Onshape · Rhino 3D · Grasshopper · AutoCAD · Parametric CAD · PrusaSlicer · Kiri:Moto · OctoPrint · GitHub · Basic Python · Raspberry Pi · ArUco markers · 8020 systems · Rapid prototyping · Production troubleshooting · Technical documentation</p><h2>Why Reframe</h2><textarea value={state.whyReframe} onChange={e=>update({whyReframe:e.target.value})} rows={12}/></aside></div>}
function MemoryMap({text,keywords}:{text:string;keywords:string[]}){const short=text.split(/\s+/).slice(0,75).join(' ')+'…';return <div className="memory"><h3>Memory map</h3><ol><li>Current role and expanded ownership</li><li>How you solve physical-system problems</li><li>Architecture + manufacturing bridge</li><li>Why that bridge fits Reframe</li></ol><h3>Five keywords</h3><p>{keywords.join(' · ')}</p><details><summary>30-second view</summary><p>{short}</p></details></div>}
function Matrix({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){return <div className="matrix-wrap"><table><thead><tr><th>Reframe requirement</th><th>Specific project & evidence</th><th>Confidence</th><th>Interview notes</th></tr></thead><tbody>{stories.map(s=><tr key={s.id}><td><strong>{s.relevance.split(' · ')[0]}</strong><small>{s.relevance}</small></td><td><strong>{s.title}</strong><p>{s.focus}</p></td><td><select aria-label={`Confidence for ${s.title}`} value={state.responsibilityRatings[`story-${s.id}`]??3} onChange={e=>update({responsibilityRatings:{...state.responsibilityRatings,[`story-${s.id}`]:Number(e.target.value)}})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select> / 5</td><td><textarea aria-label={`Notes for ${s.title}`} value={state.storyNotes[s.id]??''} onChange={e=>update({storyNotes:{...state.storyNotes,[s.id]:e.target.value}})} placeholder="Situation · Action · Result · Lesson · Relevance"/></td></tr>)}</tbody></table></div>}
function QuestionBank({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){const [category,setCategory]=useState('All');const [selected,setSelected]=useState(questions[0].id);const cats=['All',...new Set(questions.map(q=>q.category))];const visible=questions.filter(q=>category==='All'||q.category===category);const q=questions.find(x=>x.id===selected)??visible[0];const qs=state.questions[q.id]??emptyQuestion();const patch=(p:Partial<QuestionState>)=>setState(s=>({...s,questions:{...s.questions,[q.id]:{...(s.questions[q.id]??emptyQuestion()),...p}}}));return <><div className="question-tools"><label>Filter<select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>setSelected(visible[Math.floor(Math.random()*visible.length)].id)}>Random practice</button><span>{visible.length} questions</span></div><div className="question-layout"><aside className="question-list">{visible.map((x,i)=><button key={x.id} className={x.id===q.id?'active':''} onClick={()=>setSelected(x.id)}><b>{String(i+1).padStart(2,'0')}</b><span>{x.prompt}<small>{x.category}{state.questions[x.id]?.practiced?' · Practiced':''}</small></span></button>)}</aside><section className="answer-panel"><small>{q.category}</small><h2>{q.prompt}</h2><div className="confidence"><span>Confidence</span>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>patch({confidence:n})} className={qs.confidence>=n?'on':''}>{n}</button>)}</div><label>Bullet-point answer<textarea value={qs.bullets} onChange={e=>patch({bullets:e.target.value})} rows={5} placeholder="Point → evidence → role connection → concise close"/></label><label>30-second answer<textarea value={qs.short} onChange={e=>patch({short:e.target.value})} rows={5}/></label><label>90-second / STAR answer<textarea value={qs.long} onChange={e=>patch({long:e.target.value})} rows={8}/></label><AnswerCoach answer={qs.long||qs.short}/><div className="answer-actions"><label><input type="checkbox" checked={qs.practiced} onChange={e=>patch({practiced:e.target.checked,practiceCount:qs.practiceCount+(e.target.checked?1:0)})}/> Mark practiced</label><label><input type="checkbox" checked={qs.review} onChange={e=>patch({review:e.target.checked})}/> Mark for review</label><span>Practice count: {qs.practiceCount}</span></div></section></div></>}
function AnswerCoach({answer}:{answer:string}){const result=useMemo(()=>scoreAnswer(answer),[answer]);return <div className="coach"><Gauge/><div><small>RULE-BASED ANSWER COACH</small><strong>{answer?result.score:0}/100</strong></div><ul>{answer?(result.feedback.length?result.feedback:['Clear point, evidence, ownership, outcome, and role connection are all present.']):['Write an answer to receive browser-only feedback. No AI API is used.']}</ul></div>}
function Mock({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){const modes:Record<string,string[]>= {Phone:['q1','q3','q4','q2','q7','q20','q19','q33','q34','q40'],Technical:['q26','q27','q28','q29','q30','q12'],Behavioral:['q7','q16','q24','q37','q38'],Rapid:['q35','q36','q25','q22','q39']};const [mode,setMode]=useState('Phone');const [index,setIndex]=useState(-1);const [answer,setAnswer]=useState('');const ids=modes[mode];const current=questions.find(q=>q.id===ids[index]);if(index<0)return <div className="mock-start"><Headphones/><h2>Choose an interview mode</h2><p>One question at a time. Your notes stay in this browser. Speech-to-text appears only when supported.</p><div>{Object.keys(modes).map(m=><button className={mode===m?'selected':''} onClick={()=>setMode(m)} key={m}>{m}{m==='Phone'?' screen':''}</button>)}</div><button className="primary" onClick={()=>setIndex(0)}>Begin {mode.toLowerCase()} interview</button></div>;if(index>=ids.length){const weak=ids.filter(id=>(state.questions[id]?.confidence??1)<3);const avg=Math.round(ids.reduce((s,id)=>s+(state.questions[id]?.confidence??1)*20,0)/ids.length);return <div className="scorecard"><ClipboardCheck/><h2>Interview complete</h2><strong>{avg}/100</strong><p>{weak.length} answers need focused review.</p><button onClick={()=>{setState(s=>({...s,mockResults:[...s.mockResults,{date:new Date().toISOString(),mode,score:avg,weak}]}));setIndex(-1)}}>Save scorecard</button></div>}const result=scoreAnswer(answer);const saveNext=()=>{setState(s=>({...s,questions:{...s.questions,[current!.id]:{...(s.questions[current!.id]??emptyQuestion()),long:answer,practiced:true,practiceCount:(s.questions[current!.id]?.practiceCount??0)+1}}}));setAnswer('');setIndex(i=>i+1)};return <div className="mock-room"><div className="mock-progress"><span>{mode} interview</span><span>{index+1} / {ids.length}</span><i style={{width:`${(index+1)/ids.length*100}%`}}/></div><small>QUESTION {String(index+1).padStart(2,'0')}</small><h2>{current?.prompt}</h2><textarea autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} rows={10} placeholder="Capture only the points you want to remember…"/><div className="mock-score">Live structure score: <strong>{answer?result.score:0}</strong></div><div className="mock-actions"><button onClick={()=>setIndex(i=>i+1)}>Skip</button><button onClick={()=>setAnswer('')}>Repeat / clear</button><button className="primary" onClick={saveNext}>Save & next <ChevronRight/></button></div><button className="end" onClick={()=>setIndex(ids.length)}>End interview</button></div>}
function Dfma(){const framework=['Transportation limits','Module dimensions & weight','Weather exposure','Access constraints','Installation tolerances','Inspection requirements','Trade sequencing','Repetition','Automation suitability','Factory tooling','Site variability','Rework risk','Shipping damage','Labor availability','Safety','Cost','Schedule impact'];return <><div className="fundamentals">{dfmaTopics.map(([topic,definition,example,experience],i)=><article key={topic}><b>{String(i+1).padStart(2,'0')}</b><h2>{topic}</h2><p className="lead">{definition}</p><dl><dt>Modular housing example</dt><dd>{example}</dd><dt>From my experience</dt><dd>{experience}</dd><dt>Likely interview question</dt><dd>How would you apply {topic.toLowerCase()} when reviewing a module for release?</dd></dl></article>)}</div><section className="framework"><h2>Factory versus field decision framework</h2><p>Compare the whole system. Favor the environment that best controls quality and risk while preserving necessary site adaptability.</p><div>{framework.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div></section></>}
function Ask({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){const toggle=(q:string,type:'selectedAsk'|'askBackups',limit:number)=>{const list=state[type];update({[type]:list.includes(q)?list.filter(x=>x!==q):list.length<limit?[...list,q]:list} as Partial<AppState>)};return <><p className="intro-copy">Select three primary questions and two backups. Questions 1, 2, and 10 are recommended for the first phone interview.</p><div className="ask-list">{askQuestions.map((q,i)=><div key={q}><b>{String(i+1).padStart(2,'0')}</b><p>{q}</p>{[0,1,9].includes(i)?<span className="recommended">Recommended</span>:null}<button className={state.selectedAsk.includes(q)?'selected':''} onClick={()=>toggle(q,'selectedAsk',3)}>Primary</button><button className={state.askBackups.includes(q)?'selected':''} onClick={()=>toggle(q,'askBackups',2)}>Backup</button></div>)}</div><div className="selection-status">{state.selectedAsk.length}/3 primary · {state.askBackups.length}/2 backups selected</div></>}
function Final({state,update}:{state:AppState;update:(p:Partial<AppState>)=>void}){return <div className="final-sheet"><button className="print" onClick={()=>window.print()}>Print final sheet</button><header><h2>DFMA ENGINEER · PHONE INTERVIEW</h2><strong>THURSDAY, JULY 30, 2026</strong></header><section><h3>60-second introduction</h3><p>{state.intro.split(/\s+/).slice(0,145).join(' ')}</p></section><div className="final-cols"><section><h3>Why Reframe / Why DFMA</h3><p>{state.whyReframe}</p><h3>Five strongest stories</h3><ol>{stories.map(s=><li key={s.id}><strong>{s.title}</strong> — {s.relevance}</li>)}</ol><h3>Strengths</h3><p>Systems thinking · Hands-on iteration · Documentation that closes loops</p><h3>Honest development areas</h3><p>Revit/BIM depth · Reframe’s building system, codes, and modular release process</p></section><section><h3>Five Reframe facts</h3><ol><li>Physical AI and robotics company for high-performance housing</li><li>Vertically integrated from architecture through field installation</li><li>Volumetric modular production in Andover, Massachusetts</li><li>12-home Devens project: six duplexes</li><li>Regional microfactory growth, including Southern California</li></ol><h3>Five DFMA concepts</h3><p>Buildability · Tolerance stack-up · Datum strategy · First-article inspection · Factory-versus-field scope</p><h3>Questions to ask</h3><ol>{state.selectedAsk.map(q=><li key={q}>{q}</li>)}</ol></section></div><section className="checklist"><h3>Interview logistics</h3>{logistics.map(x=><label key={x}><input type="checkbox" checked={state.logistics.includes(x)} onChange={()=>update({logistics:state.logistics.includes(x)?state.logistics.filter(y=>y!==x):[...state.logistics,x]})}/><span>{x}</span></label>)}</section></div>}

export default App
